name: notes
description: Simple Notes app .

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  provider: ^4.3.1
  shared_preferences: ^0.5.8
  font_awesome_flutter: ^8.8.1
  animated_widgets: ^1.0.6
  url_launcher: ^5.5.0
  path_provider: ^1.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - images/logo.png
    - images/dark_mode_logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf